Repository twmb/franz-go, pull requests merged in 2023-02, with the labels that each got.

#340 generate: call Default before returning from ResponseKind
  generate/gen.go
  pkg/kmsg/generated.go
Labels: waiting kafka release

#304 kmsg: commit new ConsumerMemberMetadata for KIP-792
  generate/definitions/23_offset_for_leader_epoch
  generate/definitions/misc
  pkg/kmsg/generated.go
Labels: waiting kafka release

#341 generate/kmsg: support KIP-881
  generate/definitions/misc
  pkg/kmsg/generated.go
Labels: waiting kafka release

#289 generate/kmsg: support KIP-866 protocols
  generate/definitions/04_leader_and_isr
  generate/definitions/05_stop_replica
  generate/definitions/06_update_metadata
  generate/definitions/18_api_versions
  generate/definitions/62_broker_registration
  pkg/kmsg/generated.go
  pkg/kversion/kversion.go
Labels: waiting kafka release

#320 add CommitMarkedOffsets when using a custom onRevoked and AutoCommitMarks
  examples/goroutine_per_partition_consuming/autocommit_marks/main.go
  pkg/kgo/consumer_group.go
Labels: ready for minor release

#272 group balancer: support KIP-792
  README.md
  go.mod
  go.sum
  pkg/kgo/group_balancer.go
  pkg/kgo/internal/sticky/sticky.go
Labels: waiting kafka release

#294 Add Kotel plugin
  examples/hooks_and_logging/plugin_kotel/README.md
  examples/hooks_and_logging/plugin_kotel/go.mod
  examples/hooks_and_logging/plugin_kotel/go.sum
  examples/hooks_and_logging/plugin_kotel/main.go
  pkg/kgo/record_and_fetch.go
  plugin/kotel/README.md
  plugin/kotel/carrier.go
  plugin/kotel/carrier_test.go
  plugin/kotel/go.mod
  plugin/kotel/go.sum
  plugin/kotel/kotel.go
  plugin/kotel/kotel_test.go
  plugin/kotel/meter.go
  plugin/kotel/meter_test.go
  plugin/kotel/tracer.go
  plugin/kotel/tracer_test.go
  plugin/kotel/version.go
Labels: plugin
