Repository twmb/franz-go, pull requests merged in 2024-10, with the labels that each got.

#832 kgo: fix potential deadlock when reaching max buffered (records|bytes)
  .golangci.yml
  generate/gen.go
  pkg/kgo/produce_request_test.go
  pkg/kgo/producer.go
  pkg/kgo/record_and_fetch.go
Labels: patch

#760 kgo: add AllowRebalance and CloseAllowingRebalance to GroupTransactSession
  pkg/kgo/txn.go
Labels: minor

#789 kgo: export the wrapped error from ErrGroupSession
  pkg/kgo/errors.go
Labels: minor

#794 kgo: add TopicID to the FetchTopic type
  pkg/kgo/record_and_fetch.go
  pkg/kgo/source.go
Labels: minor

#814 kadm: add `NewOffsetFromRecord` helper function
  pkg/kadm/kadm.go
Labels: kadm

#829 Add Opts method for sr.Client
  pkg/sr/client.go
Labels: sr

#834 kgo: ignore OOOSN where possible
  pkg/kgo/config.go
  pkg/kgo/metadata.go
  pkg/kgo/sink.go
Labels: patch

#835 sr: add StatusCode to ResponseError, and message if the body is empty
  pkg/sr/client.go
Labels: sr

#838 kgo: do not add all topics to internal tps map when regex consuming
  pkg/kgo/consumer.go
  pkg/kgo/consumer_direct.go
  pkg/kgo/consumer_direct_test.go
  pkg/kgo/consumer_group.go
  pkg/kgo/metadata.go
Labels: patch
