Repository twmb/franz-go, pull requests merged in 2025-04, with the labels that each got.

#921 kgo: fix cancellation of a fetch in manageFetchConcurrency
  .gitignore
  pkg/kgo/consumer.go
Labels: patch

#857 Bug | BasicLogger Panics When `len(keyvals)` is 1
  pkg/kgo/logger.go
Labels: patch, ready

#949 kgo: allow outstanding produce requests to be context canceled if the user disables idempotency
  pkg/kgo/sink.go
Labels: ready

#896 kgo: add Client.RequestCachedMetadata
  pkg/kgo/client.go
  pkg/kgo/group_balancer.go
  pkg/kgo/metadata.go
Labels: minor, ready

#904 kgo: allow compressor & decompressors to be entirely user driven; allow users to inject memory pools
  .github/workflows/lint-and-test.yml
  .golangci.yml
  pkg/kfake/cluster.go
  pkg/kgo/client.go
  pkg/kgo/compression.go
  pkg/kgo/compression_test.go
  pkg/kgo/config.go
  pkg/kgo/consumer_direct_test.go
  pkg/kgo/consumer_group.go
  pkg/kgo/group_test.go
  pkg/kgo/helpers_test.go
  pkg/kgo/hooks.go
  pkg/kgo/pools.go
  pkg/kgo/produce_request_test.go
  pkg/kgo/producer.go
  pkg/kgo/record_and_fetch.go
  pkg/kgo/record_formatter.go
  pkg/kgo/sink.go
  pkg/kgo/source.go
  pkg/kgo/txn_test.go
Labels: enhancement, minor, ready

#907 kgo: add ctx field to client cfg
  pkg/kgo/client.go
  pkg/kgo/config.go
Labels: enhancement, ready

#944 kgo: fix off-by-one with retries accounting
  pkg/kgo/producer.go
  pkg/kgo/sink.go
Labels: ready

#948 kgo: add DefaultProduceTopicAlways ProducerOpt
  pkg/kgo/client.go
  pkg/kgo/config.go
  pkg/kgo/producer.go
Labels: ready

#941 kotel: consumer span links
  plugin/kotel/tracer.go
Labels: plugin, ready

#945 kgo: periodically redirect back to the leader & add config option
  pkg/kgo/client.go
  pkg/kgo/config.go
  pkg/kgo/source.go
Labels: minor, ready

#839 kgo: add EnsureProduceConnectionIsOpen
  pkg/kfake/18_api_versions.go
  pkg/kgo/broker.go
  pkg/kgo/producer.go
Labels: in design
