Repository twmb/franz-go, pull requests merged in 2025-01, with the labels that each got.

#870 kadm: add func to decode AuthorizedOperations
  pkg/kadm/acls.go
  pkg/kadm/acls_test.go
Labels: kadm

#846 Fix handling of invalid base offsets
  pkg/kgo/producer.go
  pkg/kgo/source.go
Labels: patch

#867 Add PreReq option sr API
  pkg/sr/client.go
  pkg/sr/client_test.go
  pkg/sr/clientopt.go
Labels: sr

#878 kgo: broadcast batch finishes in one big blast
  pkg/kgo/producer.go
Labels: patch

#882 kgo: fix accounting when topics/partitions are {,un}paused for PollRecords
  pkg/kgo/consumer_direct_test.go
  pkg/kgo/hooks.go
  pkg/kgo/source.go
Labels: patch

#883 kgo: return decompression errors while consuming
  pkg/kgo/errors.go
  pkg/kgo/source.go
Labels: patch

#886 kgo: redirect back to the leader on KIP-392 case 3 failure
  pkg/kgo/consumer.go
  pkg/kgo/source.go
Labels: patch
